all:
	pdflatex Presentazione\ PACS.tex > /dev/null ;\
	bibtex Presentazione\ PACS> /dev/null;\
	pdflatex Presentazione\ PACS.tex > /dev/null;\
	pdflatex Presentazione\ PACS.tex > /dev/null;

clean:
	rm -f *.aux *.nav *.out *.snm *.toc *.pdf *.blg *.log *.bbl *.run.xml *.bib *.vrb
	
